/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: weather_data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "weather_data.pb-c.h"
void   weather__v1__weather_data__time_info__init
                     (Weather__V1__WeatherData__TimeInfo         *message)
{
  static const Weather__V1__WeatherData__TimeInfo init_value = WEATHER__V1__WEATHER_DATA__TIME_INFO__INIT;
  *message = init_value;
}
void   weather__v1__weather_data__date_info__init
                     (Weather__V1__WeatherData__DateInfo         *message)
{
  static const Weather__V1__WeatherData__DateInfo init_value = WEATHER__V1__WEATHER_DATA__DATE_INFO__INIT;
  *message = init_value;
}
void   weather__v1__weather_data__weather_info__init
                     (Weather__V1__WeatherData__WeatherInfo         *message)
{
  static const Weather__V1__WeatherData__WeatherInfo init_value = WEATHER__V1__WEATHER_DATA__WEATHER_INFO__INIT;
  *message = init_value;
}
void   weather__v1__weather_data__init
                     (Weather__V1__WeatherData         *message)
{
  static const Weather__V1__WeatherData init_value = WEATHER__V1__WEATHER_DATA__INIT;
  *message = init_value;
}
size_t weather__v1__weather_data__get_packed_size
                     (const Weather__V1__WeatherData *message)
{
  assert(message->base.descriptor == &weather__v1__weather_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t weather__v1__weather_data__pack
                     (const Weather__V1__WeatherData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &weather__v1__weather_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t weather__v1__weather_data__pack_to_buffer
                     (const Weather__V1__WeatherData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &weather__v1__weather_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Weather__V1__WeatherData *
       weather__v1__weather_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Weather__V1__WeatherData *)
     protobuf_c_message_unpack (&weather__v1__weather_data__descriptor,
                                allocator, len, data);
}
void   weather__v1__weather_data__free_unpacked
                     (Weather__V1__WeatherData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &weather__v1__weather_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor weather__v1__weather_data__time_info__field_descriptors[2] =
{
  {
    "hours",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__TimeInfo, hours),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minutes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__TimeInfo, minutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__v1__weather_data__time_info__field_indices_by_name[] = {
  0,   /* field[0] = hours */
  1,   /* field[1] = minutes */
};
static const ProtobufCIntRange weather__v1__weather_data__time_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor weather__v1__weather_data__time_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.v1.WeatherData.TimeInfo",
  "TimeInfo",
  "Weather__V1__WeatherData__TimeInfo",
  "weather.v1",
  sizeof(Weather__V1__WeatherData__TimeInfo),
  2,
  weather__v1__weather_data__time_info__field_descriptors,
  weather__v1__weather_data__time_info__field_indices_by_name,
  1,  weather__v1__weather_data__time_info__number_ranges,
  (ProtobufCMessageInit) weather__v1__weather_data__time_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor weather__v1__weather_data__date_info__field_descriptors[4] =
{
  {
    "day_of_week",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__DateInfo, day_of_week),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__DateInfo, month),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__DateInfo, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "year",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__DateInfo, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__v1__weather_data__date_info__field_indices_by_name[] = {
  2,   /* field[2] = day */
  0,   /* field[0] = day_of_week */
  1,   /* field[1] = month */
  3,   /* field[3] = year */
};
static const ProtobufCIntRange weather__v1__weather_data__date_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor weather__v1__weather_data__date_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.v1.WeatherData.DateInfo",
  "DateInfo",
  "Weather__V1__WeatherData__DateInfo",
  "weather.v1",
  sizeof(Weather__V1__WeatherData__DateInfo),
  4,
  weather__v1__weather_data__date_info__field_descriptors,
  weather__v1__weather_data__date_info__field_indices_by_name,
  1,  weather__v1__weather_data__date_info__number_ranges,
  (ProtobufCMessageInit) weather__v1__weather_data__date_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor weather__v1__weather_data__weather_info__field_descriptors[11] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_speed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_direction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rain_last_hour",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, rain_last_hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solar_radiation",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, solar_radiation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidex",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, humidex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dew_point",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, dew_point),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_chill",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, wind_chill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snow_depth",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData__WeatherInfo, snow_depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__v1__weather_data__weather_info__field_indices_by_name[] = {
  8,   /* field[8] = dew_point */
  7,   /* field[7] = humidex */
  1,   /* field[1] = humidity */
  2,   /* field[2] = pressure */
  5,   /* field[5] = rain_last_hour */
  10,   /* field[10] = snow_depth */
  6,   /* field[6] = solar_radiation */
  0,   /* field[0] = temperature */
  9,   /* field[9] = wind_chill */
  4,   /* field[4] = wind_direction */
  3,   /* field[3] = wind_speed */
};
static const ProtobufCIntRange weather__v1__weather_data__weather_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor weather__v1__weather_data__weather_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.v1.WeatherData.WeatherInfo",
  "WeatherInfo",
  "Weather__V1__WeatherData__WeatherInfo",
  "weather.v1",
  sizeof(Weather__V1__WeatherData__WeatherInfo),
  11,
  weather__v1__weather_data__weather_info__field_descriptors,
  weather__v1__weather_data__weather_info__field_indices_by_name,
  1,  weather__v1__weather_data__weather_info__number_ranges,
  (ProtobufCMessageInit) weather__v1__weather_data__weather_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor weather__v1__weather_data__field_descriptors[3] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData, time),
    &weather__v1__weather_data__time_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "date",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData, date),
    &weather__v1__weather_data__date_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weather",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Weather__V1__WeatherData, weather),
    &weather__v1__weather_data__weather_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__v1__weather_data__field_indices_by_name[] = {
  1,   /* field[1] = date */
  0,   /* field[0] = time */
  2,   /* field[2] = weather */
};
static const ProtobufCIntRange weather__v1__weather_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor weather__v1__weather_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.v1.WeatherData",
  "WeatherData",
  "Weather__V1__WeatherData",
  "weather.v1",
  sizeof(Weather__V1__WeatherData),
  3,
  weather__v1__weather_data__field_descriptors,
  weather__v1__weather_data__field_indices_by_name,
  1,  weather__v1__weather_data__number_ranges,
  (ProtobufCMessageInit) weather__v1__weather_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
