/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: weather_data.proto */

#ifndef PROTOBUF_C_weather_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_weather_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>
#include <stdint.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct Weather__V1__WeatherData Weather__V1__WeatherData;
typedef struct Weather__V1__WeatherData__TimeInfo
    Weather__V1__WeatherData__TimeInfo;
typedef struct Weather__V1__WeatherData__DateInfo
    Weather__V1__WeatherData__DateInfo;
typedef struct Weather__V1__WeatherData__WeatherInfo
    Weather__V1__WeatherData__WeatherInfo;

/* --- enums --- */

/* --- messages --- */

struct Weather__V1__WeatherData__TimeInfo {
  ProtobufCMessage base;
  int32_t hours;
  int32_t minutes;
};
#define WEATHER__V1__WEATHER_DATA__TIME_INFO__INIT                             \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(&weather__v1__weather_data__time_info__descriptor) \
    , 0, 0                                                                     \
  }

struct Weather__V1__WeatherData__DateInfo {
  ProtobufCMessage base;
  char *day_of_week;
  char *month;
  int32_t day;
  int32_t year;
};
#define WEATHER__V1__WEATHER_DATA__DATE_INFO__INIT                             \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(&weather__v1__weather_data__date_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0   \
  }

struct Weather__V1__WeatherData__WeatherInfo {
  ProtobufCMessage base;
  float temperature;
  float humidity;
  float pressure;
  float wind_speed;
  float wind_direction;
  float rain_last_hour;
  float solar_radiation;
  float humidex;
  float dew_point;
  float wind_chill;
  int32_t snow_depth;
};
#define WEATHER__V1__WEATHER_DATA__WEATHER_INFO__INIT                          \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(                                                   \
        &weather__v1__weather_data__weather_info__descriptor)                  \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0                                          \
  }

struct Weather__V1__WeatherData {
  ProtobufCMessage base;
  Weather__V1__WeatherData__TimeInfo *time;
  Weather__V1__WeatherData__DateInfo *date;
  Weather__V1__WeatherData__WeatherInfo *weather;
};
#define WEATHER__V1__WEATHER_DATA__INIT                                        \
  {                                                                            \
    PROTOBUF_C_MESSAGE_INIT(&weather__v1__weather_data__descriptor)            \
    , NULL, NULL, NULL                                                         \
  }

/* Weather__V1__WeatherData__TimeInfo methods */
void weather__v1__weather_data__time_info__init(
    Weather__V1__WeatherData__TimeInfo *message);
/* Weather__V1__WeatherData__DateInfo methods */
void weather__v1__weather_data__date_info__init(
    Weather__V1__WeatherData__DateInfo *message);
/* Weather__V1__WeatherData__WeatherInfo methods */
void weather__v1__weather_data__weather_info__init(
    Weather__V1__WeatherData__WeatherInfo *message);
/* Weather__V1__WeatherData methods */
void weather__v1__weather_data__init(Weather__V1__WeatherData *message);
size_t weather__v1__weather_data__get_packed_size(
    const Weather__V1__WeatherData *message);
size_t weather__v1__weather_data__pack(const Weather__V1__WeatherData *message,
                                       uint8_t *out);
size_t weather__v1__weather_data__pack_to_buffer(
    const Weather__V1__WeatherData *message, ProtobufCBuffer *buffer);
Weather__V1__WeatherData *
weather__v1__weather_data__unpack(ProtobufCAllocator *allocator, size_t len,
                                  const uint8_t *data);
void weather__v1__weather_data__free_unpacked(Weather__V1__WeatherData *message,
                                              ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Weather__V1__WeatherData__TimeInfo_Closure)(
    const Weather__V1__WeatherData__TimeInfo *message, void *closure_data);
typedef void (*Weather__V1__WeatherData__DateInfo_Closure)(
    const Weather__V1__WeatherData__DateInfo *message, void *closure_data);
typedef void (*Weather__V1__WeatherData__WeatherInfo_Closure)(
    const Weather__V1__WeatherData__WeatherInfo *message, void *closure_data);
typedef void (*Weather__V1__WeatherData_Closure)(
    const Weather__V1__WeatherData *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor weather__v1__weather_data__descriptor;
extern const ProtobufCMessageDescriptor
    weather__v1__weather_data__time_info__descriptor;
extern const ProtobufCMessageDescriptor
    weather__v1__weather_data__date_info__descriptor;
extern const ProtobufCMessageDescriptor
    weather__v1__weather_data__weather_info__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_weather_5fdata_2eproto__INCLUDED */
